from __future__ import annotations

import platform
import time
import json
from dataclasses import asdict, dataclass
from pathlib import Path
from typing import Dict, Iterable, List, Optional, Tuple

import cv2
import numpy as np

import config


@dataclass
class CameraSettings:
    width: int = config.CAMERA_WIDTH
    height: int = config.CAMERA_HEIGHT
    fps: int = config.CAMERA_FPS
    backend: str = "auto"
    fourcc: str = config.CAMERA_FOURCC
    auto_exposure: bool = config.CAMERA_AUTO_EXPOSURE
    exposure: Optional[float] = config.CAMERA_EXPOSURE
    brightness: Optional[float] = None
    contrast: Optional[float] = None
    gain: Optional[float] = None
    autofocus: Optional[bool] = None
    focus: Optional[float] = None


@dataclass
class CameraMetrics:
    mean_luma: float
    overexposed_ratio: float
    underexposed_ratio: float
    contrast: float
    sharpness: float
    score: float


@dataclass
class CalibrationResult:
    settings: CameraSettings
    metrics: CameraMetrics
    profile_path: str


def create_capture(camera_index: int, backend: str = "auto") -> cv2.VideoCapture:
    backend_id = _backend_id(backend)
    if backend_id is not None:
        return cv2.VideoCapture(camera_index, backend_id)
    if platform.system() == "Windows":
        return cv2.VideoCapture(camera_index, cv2.CAP_DSHOW)
    return cv2.VideoCapture(camera_index)


def configure_capture(cap: cv2.VideoCapture, settings: CameraSettings) -> Dict[str, float]:
    if settings.fourcc:
        cap.set(cv2.CAP_PROP_FOURCC, cv2.VideoWriter_fourcc(*settings.fourcc[:4]))
    cap.set(cv2.CAP_PROP_FRAME_WIDTH, settings.width)
    cap.set(cv2.CAP_PROP_FRAME_HEIGHT, settings.height)
    cap.set(cv2.CAP_PROP_FPS, settings.fps)
    _set_auto_exposure(cap, settings.auto_exposure)

    if settings.exposure is not None:
        cap.set(cv2.CAP_PROP_EXPOSURE, float(settings.exposure))
    _set_optional(cap, cv2.CAP_PROP_BRIGHTNESS, settings.brightness)
    _set_optional(cap, cv2.CAP_PROP_CONTRAST, settings.contrast)
    _set_optional(cap, cv2.CAP_PROP_GAIN, settings.gain)
    if settings.autofocus is not None and hasattr(cv2, "CAP_PROP_AUTOFOCUS"):
        cap.set(cv2.CAP_PROP_AUTOFOCUS, 1 if settings.autofocus else 0)
    if settings.focus is not None and hasattr(cv2, "CAP_PROP_FOCUS"):
        cap.set(cv2.CAP_PROP_FOCUS, float(settings.focus))

    return read_capture_settings(cap)


def read_capture_settings(cap: cv2.VideoCapture) -> Dict[str, float]:
    return {
        "width": cap.get(cv2.CAP_PROP_FRAME_WIDTH),
        "height": cap.get(cv2.CAP_PROP_FRAME_HEIGHT),
        "fps": cap.get(cv2.CAP_PROP_FPS),
        "exposure": cap.get(cv2.CAP_PROP_EXPOSURE),
        "brightness": cap.get(cv2.CAP_PROP_BRIGHTNESS),
        "contrast": cap.get(cv2.CAP_PROP_CONTRAST),
        "gain": cap.get(cv2.CAP_PROP_GAIN),
        "focus": cap.get(cv2.CAP_PROP_FOCUS) if hasattr(cv2, "CAP_PROP_FOCUS") else -1.0,
        "auto_exposure": cap.get(cv2.CAP_PROP_AUTO_EXPOSURE),
    }


def load_camera_profile(path: str = config.CAMERA_PROFILE_PATH) -> Optional[Dict[str, float | int | str | bool | None]]:
    profile_path = Path(path)
    if not profile_path.exists():
        return None
    try:
        data = json.loads(profile_path.read_text(encoding="utf-8"))
    except (OSError, json.JSONDecodeError):
        return None
    settings = data.get("settings", data)
    if not isinstance(settings, dict):
        return None
    return settings


def save_camera_profile(
    path: str,
    settings: CameraSettings,
    metrics: CameraMetrics,
) -> None:
    profile_path = Path(path)
    payload = {
        "settings": asdict(settings),
        "metrics": asdict(metrics),
        "note": "Generated by `python main.py --calibrate-camera`.",
    }
    profile_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")


def list_cameras(max_index: int = 5, backend: str = "auto") -> None:
    if platform.system() == "Windows":
        print("Windows camera probe:")
    else:
        devices = sorted(str(path) for path in Path("/dev").glob("video*"))
        print("Linux video devices:")
        if devices:
            for device in devices:
                print(f"  {device}")
        else:
            print("  none found under /dev/video*")
        print("\nOpenCV camera probe:")

    found = False
    for index in range(max_index):
        cap = create_capture(index, backend)
        ok = cap.isOpened()
        if ok:
            found = True
            width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
            height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))
            fps = cap.get(cv2.CAP_PROP_FPS)
            print(f"  index {index}: OK ({width}x{height}, fps={fps:0.1f})")
        cap.release()
    if not found:
        print("  no usable camera indices found")


def tracking_roi(frame_shape: Tuple[int, int, int], y_min_ratio: float = config.TRACKING_ROI_Y_MIN) -> Tuple[int, int, int, int]:
    height, width = frame_shape[:2]
    y1 = int(height * y_min_ratio)
    return (0, max(0, y1), width, height)


def enhance_frame(frame, mode: str = "auto"):
    if mode == "none":
        return frame
    if mode == "clahe":
        return _clahe(frame)
    if mode == "auto":
        return _auto_tone(frame)
    return frame


def _auto_tone(frame):
    lab = cv2.cvtColor(frame, cv2.COLOR_BGR2LAB)
    l_channel, a_channel, b_channel = cv2.split(lab)
    p95 = float(np.percentile(l_channel, 95))
    p5 = float(np.percentile(l_channel, 5))

    if p95 > 235.0:
        l_channel = np.clip(l_channel.astype(np.float32) * (220.0 / max(p95, 1.0)), 0, 255).astype(np.uint8)
    if p5 < 8.0 and p95 < 190.0:
        l_channel = np.clip(l_channel.astype(np.float32) * 1.15 + 8.0, 0, 255).astype(np.uint8)

    clahe = cv2.createCLAHE(clipLimit=1.6, tileGridSize=(8, 8))
    l_channel = clahe.apply(l_channel)
    return cv2.cvtColor(cv2.merge((l_channel, a_channel, b_channel)), cv2.COLOR_LAB2BGR)


def measure_frame_quality(frame, roi: Optional[Tuple[int, int, int, int]] = None) -> CameraMetrics:
    if roi is not None:
        x1, y1, x2, y2 = roi
        height, width = frame.shape[:2]
        x1 = max(0, min(width - 1, x1))
        x2 = max(x1 + 1, min(width, x2))
        y1 = max(0, min(height - 1, y1))
        y2 = max(y1 + 1, min(height, y2))
        frame = frame[y1:y2, x1:x2]

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    mean_luma = float(np.mean(gray))
    overexposed_ratio = float(np.mean(gray >= 245))
    underexposed_ratio = float(np.mean(gray <= 8))
    contrast = float(np.std(gray))
    sharpness = float(cv2.Laplacian(gray, cv2.CV_64F).var())

    exposure_penalty = 1.0
    exposure_penalty *= max(0.01, 1.0 - overexposed_ratio * 12.0)
    exposure_penalty *= max(0.25, 1.0 - underexposed_ratio * 2.0)
    exposure_penalty *= max(0.12, 1.0 - abs(mean_luma - 115.0) / 120.0)
    score = np.log1p(sharpness) * exposure_penalty + 0.018 * contrast
    return CameraMetrics(
        mean_luma=mean_luma,
        overexposed_ratio=overexposed_ratio,
        underexposed_ratio=underexposed_ratio,
        contrast=contrast,
        sharpness=sharpness,
        score=float(score),
    )


def calibrate_camera(
    camera_index: int,
    base_settings: CameraSettings,
    profile_path: str = config.CAMERA_PROFILE_PATH,
    exposures: Optional[Iterable[float]] = None,
    resolutions: Optional[Iterable[Tuple[int, int]]] = None,
    focus_values: Optional[Iterable[float]] = None,
    sample_frames: int = 8,
    warmup_frames: int = 8,
    show_preview: bool = True,
) -> CalibrationResult:
    cap = create_capture(camera_index, base_settings.backend)
    if not cap.isOpened():
        raise RuntimeError(f"Could not open camera index {camera_index} for calibration.")

    try:
        base = CameraSettings(**asdict(base_settings))
        base.auto_exposure = False
        base.gain = 0.0 if base.gain is None else base.gain
        resolution_candidates = list(resolutions or [(base.width, base.height)])
        exposure_candidates = list(exposures or config.CALIBRATION_EXPOSURES)

        best_settings: Optional[CameraSettings] = None
        best_metrics: Optional[CameraMetrics] = None
        for width, height in resolution_candidates:
            settings = CameraSettings(**asdict(base))
            settings.width = int(width)
            settings.height = int(height)
            actual = configure_capture(cap, settings)
            _flush_frames(cap, warmup_frames)

            print(f"\nResolution candidate: requested={width}x{height} actual={int(actual['width'])}x{int(actual['height'])}")

            candidate_settings, candidate_metrics = _sweep_exposure(
                cap=cap,
                settings=settings,
                exposures=exposure_candidates,
                roi=None,
                sample_frames=sample_frames,
                warmup_frames=warmup_frames,
                show_preview=show_preview,
            )
            candidate_settings.width = int(actual["width"])
            candidate_settings.height = int(actual["height"])
            if best_metrics is None or candidate_metrics.score > best_metrics.score:
                best_settings = candidate_settings
                best_metrics = candidate_metrics

        if best_settings is None or best_metrics is None:
            raise RuntimeError("Calibration could not find a usable camera setting.")
        configure_capture(cap, best_settings)
        _flush_frames(cap, warmup_frames)
        if focus_values:
            best_settings, best_metrics = _sweep_focus(
                cap=cap,
                settings=best_settings,
                focus_values=list(focus_values),
                roi=None,
                sample_frames=sample_frames,
                warmup_frames=max(4, warmup_frames // 2),
                show_preview=show_preview,
            )

        save_camera_profile(profile_path, best_settings, best_metrics)
        return CalibrationResult(settings=best_settings, metrics=best_metrics, profile_path=profile_path)
    finally:
        cap.release()
        if show_preview:
            cv2.destroyAllWindows()


def _sweep_exposure(
    cap: cv2.VideoCapture,
    settings: CameraSettings,
    exposures: List[float],
    roi: Optional[Tuple[int, int, int, int]],
    sample_frames: int,
    warmup_frames: int,
    show_preview: bool,
) -> Tuple[CameraSettings, CameraMetrics]:
    best_settings = CameraSettings(**asdict(settings))
    best_metrics: Optional[CameraMetrics] = None

    for exposure in exposures:
        trial = CameraSettings(**asdict(settings))
        trial.auto_exposure = False
        trial.exposure = float(exposure)
        configure_capture(cap, trial)
        _flush_frames(cap, warmup_frames)
        metrics = _sample_metrics(cap, roi, sample_frames, f"exposure={exposure}", show_preview)
        print(_format_metrics(f"exposure {exposure:>5}", metrics))
        if best_metrics is None or metrics.score > best_metrics.score:
            best_metrics = metrics
            best_settings = trial

    if best_metrics is None:
        raise RuntimeError("Calibration could not read frames while sweeping exposure.")
    configure_capture(cap, best_settings)
    return best_settings, best_metrics


def _sweep_focus(
    cap: cv2.VideoCapture,
    settings: CameraSettings,
    focus_values: List[float],
    roi: Optional[Tuple[int, int, int, int]],
    sample_frames: int,
    warmup_frames: int,
    show_preview: bool,
) -> Tuple[CameraSettings, CameraMetrics]:
    best_settings = CameraSettings(**asdict(settings))
    best_metrics: Optional[CameraMetrics] = None

    for focus in focus_values:
        trial = CameraSettings(**asdict(settings))
        trial.autofocus = False
        trial.focus = float(focus)
        configure_capture(cap, trial)
        _flush_frames(cap, warmup_frames)
        metrics = _sample_metrics(cap, roi, sample_frames, f"focus={focus}", show_preview)
        print(_format_metrics(f"focus {focus:>5}", metrics))
        if best_metrics is None or metrics.score > best_metrics.score:
            best_metrics = metrics
            best_settings = trial

    if best_metrics is None:
        raise RuntimeError("Calibration could not read frames while sweeping focus.")
    configure_capture(cap, best_settings)
    return best_settings, best_metrics


def _sample_metrics(
    cap: cv2.VideoCapture,
    roi: Optional[Tuple[int, int, int, int]],
    sample_frames: int,
    label: str,
    show_preview: bool,
) -> CameraMetrics:
    metrics_list: List[CameraMetrics] = []
    for _ in range(sample_frames):
        ok, frame = cap.read()
        if not ok or frame is None:
            continue
        metrics = measure_frame_quality(frame, roi)
        metrics_list.append(metrics)
        if show_preview:
            preview = frame.copy()
            if roi is not None:
                x1, y1, x2, y2 = roi
                cv2.rectangle(preview, (x1, y1), (x2, y2), (40, 220, 255), 2)
            _draw_calibration_overlay(preview, label, metrics)
            cv2.imshow("AirDesk Camera Calibration", preview)
            if cv2.waitKey(1) & 0xFF == ord("q"):
                break
    if not metrics_list:
        raise RuntimeError("Camera returned no frames during calibration.")
    return _average_metrics(metrics_list)


def _average_metrics(metrics_list: List[CameraMetrics]) -> CameraMetrics:
    return CameraMetrics(
        mean_luma=float(np.mean([m.mean_luma for m in metrics_list])),
        overexposed_ratio=float(np.mean([m.overexposed_ratio for m in metrics_list])),
        underexposed_ratio=float(np.mean([m.underexposed_ratio for m in metrics_list])),
        contrast=float(np.mean([m.contrast for m in metrics_list])),
        sharpness=float(np.mean([m.sharpness for m in metrics_list])),
        score=float(np.mean([m.score for m in metrics_list])),
    )


def _flush_frames(cap: cv2.VideoCapture, count: int) -> None:
    for _ in range(count):
        cap.read()
        time.sleep(0.01)


def _draw_calibration_overlay(frame, label: str, metrics: CameraMetrics) -> None:
    text_lines = [
        f"Calibrating {label}",
        f"score={metrics.score:.2f} sharp={metrics.sharpness:.0f}",
        f"luma={metrics.mean_luma:.0f} over={metrics.overexposed_ratio*100:.1f}%",
        "Press q to stop preview",
    ]
    x, y = 18, 34
    cv2.rectangle(frame, (10, 10), (430, 135), (20, 20, 20), -1)
    for line in text_lines:
        cv2.putText(frame, line, (x, y), cv2.FONT_HERSHEY_SIMPLEX, 0.58, (245, 245, 245), 2)
        y += 28


def _format_metrics(label: str, metrics: CameraMetrics) -> str:
    return (
        f"{label}: score={metrics.score:5.2f} sharp={metrics.sharpness:8.1f} "
        f"luma={metrics.mean_luma:6.1f} over={metrics.overexposed_ratio*100:5.1f}% "
        f"under={metrics.underexposed_ratio*100:5.1f}% contrast={metrics.contrast:5.1f}"
    )


def _clahe(frame):
    lab = cv2.cvtColor(frame, cv2.COLOR_BGR2LAB)
    l_channel, a_channel, b_channel = cv2.split(lab)
    clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(8, 8))
    l_channel = clahe.apply(l_channel)
    return cv2.cvtColor(cv2.merge((l_channel, a_channel, b_channel)), cv2.COLOR_LAB2BGR)


def _set_optional(cap: cv2.VideoCapture, prop: int, value: Optional[float]) -> None:
    if value is not None:
        cap.set(prop, float(value))


def _set_auto_exposure(cap: cv2.VideoCapture, enabled: bool) -> None:
    if platform.system() == "Windows":
        cap.set(cv2.CAP_PROP_AUTO_EXPOSURE, 0.75 if enabled else 0.25)
    else:
        cap.set(cv2.CAP_PROP_AUTO_EXPOSURE, 3 if enabled else 1)


def _backend_id(backend: str) -> Optional[int]:
    normalized = backend.lower()
    if normalized in {"auto", "default"}:
        return None
    if normalized == "dshow":
        return cv2.CAP_DSHOW
    if normalized == "msmf":
        return cv2.CAP_MSMF
    if normalized == "v4l2":
        return cv2.CAP_V4L2
    raise ValueError(f"Unsupported camera backend: {backend}")
