"""Central configuration for AirDesk Instrument."""

CAMERA_WIDTH = 1280
CAMERA_HEIGHT = 720
CAMERA_FPS = 30
CAMERA_EXPOSURE = -6.0
CAMERA_AUTO_EXPOSURE = False
CAMERA_FOURCC = "MJPG"
CAMERA_PROFILE_PATH = "camera_profile.json"
CALIBRATION_EXPOSURES = [-3.0, -4.0, -5.0, -6.0, -7.0, -8.0, -9.0]
CALIBRATION_FOCUS_VALUES = [0, 20, 40, 60, 80, 110, 140, 180, 220, 255]
CALIBRATION_RESOLUTIONS = [(640, 480), (1280, 720), (1920, 1080)]

ROI_X_MIN = 0.10
ROI_X_MAX = 0.90
ROI_Y_MIN = 0.45
ROI_Y_MAX = 0.90

PIANO_ROI_X_MIN = 0.00
PIANO_ROI_X_MAX = 1.00
PIANO_ROI_Y_MIN = 0.38
PIANO_ROI_Y_MAX = 1.00

HIT_VELOCITY_THRESHOLD = 850.0
PIANO_HIT_VELOCITY_THRESHOLD = 150.0
PIANO_CROSSING_VELOCITY_THRESHOLD = 55.0
HIT_MIN_VELOCITY = 650.0
HIT_MAX_VELOCITY = 2400.0
HIT_COOLDOWN = 0.16
PRESS_RATIO = 0.55
RELEASE_RATIO = 0.40
PIANO_PRESS_RATIO = 0.35
PIANO_RELEASE_RATIO = 0.30
PIANO_ARM_RATIO = 0.28
PIANO_LIFT_VELOCITY_THRESHOLD = 45.0
PIANO_FALLING_VELOCITY_THRESHOLD = 38.0
PIANO_ARM_MIN_LIFT_PX = 16.0
PIANO_RELEASE_STABLE_FRAMES = 2
PIANO_MIN_FALL_FRAMES = 1
PIANO_STRIKE_MIN_DROP_PX = 12.0
PIANO_STRIKE_MIN_VELOCITY = 80.0
PIANO_RELEASE_LIFT_PX = 12.0
PIANO_RELEASE_MIN_UP_VELOCITY = 18.0
PIANO_RELEASE_STRONG_LIFT_MULTIPLIER = 1.55
PIANO_DEPTH_RELEASE_GUARD = True
PIANO_DEPTH_RELEASE_GUARD_ASSIST = False
PIANO_RELEASE_MIN_NET_LIFT_PX = 14.0
PIANO_RELEASE_MAX_SINGLE_FRAME_LIFT_PX = 42.0
PIANO_JITTER_GUARD_ENABLED = True
PIANO_STRIKE_MIN_NET_DROP_PX = 9.0
PIANO_STRIKE_MAX_SINGLE_FRAME_DROP_PX = 64.0
PIANO_STRIKE_STRONG_DROP_MULTIPLIER = 1.7
PIANO_STRIKE_STRONG_VELOCITY_MULTIPLIER = 1.45
PIANO_USE_RELATIVE_FINGER_MOTION = True
PIANO_MAX_HITS_PER_HAND_PER_FRAME = 1
PIANO_THUMB_SCORE_WEIGHT = 0.82
PIANO_HIT_MIN_VELOCITY = 60.0
PIANO_HIT_MAX_VELOCITY = 420.0
PIANO_MIN_VOLUME = 0.22
PIANO_HIT_X_MARGIN_RATIO = 0.06
PIANO_HIT_TOP_MARGIN_RATIO = 0.28
PIANO_HIT_BOTTOM_MARGIN_RATIO = 0.18
VELOCITY_SMOOTHING_ALPHA = 0.65
FINGER_TIP_IDS = (4, 8, 12, 16, 20)
TRIGGER_FINGER_IDS = (4, 8, 12, 16, 20)

GESTURE_STABLE_FRAMES = 8
GESTURE_COOLDOWN = 1.0

LOOP_MIN_DURATION = 1.0

AUDIO_SAMPLE_RATE = 44100
AUDIO_CHANNELS = 2
AUDIO_BUFFER = 512
AUDIO_MIXER_CHANNELS = 32

HIGHLIGHT_SECONDS = 0.16
TRAIL_LENGTH = 18

TRACKING_ROI_Y_MIN = 0.35
TRACKING_MAX_WIDTH = 416
LANDMARK_SMOOTHING_ALPHA = 0.72
DEBUG_METRICS_INTERVAL = 0.5
HAND_MIN_DETECTION_CONFIDENCE = 0.45
HAND_MIN_TRACKING_CONFIDENCE = 0.45
TRACKING_FULL_FRAME_REACQUIRE = True
TRACKING_BRIDGE_MISSED_FRAMES = True
TRACKING_BRIDGE_MAX_FRAMES = 5
TRACKING_BRIDGE_MIN_POINTS = 3
TRACKING_BRIDGE_MAX_FLOW_ERROR = 32.0
TRACKING_BRIDGE_MAX_POINT_STEP_PX = 46.0
TRACKING_REACQUIRE_HIT_BLOCK_FRAMES = 2
PIANO_BLOCK_UNSTABLE_LANDMARK_HITS = True

# MediaPipe still provides the coarse 21-point hand pose, but these options add
# a lightweight OpenCV Lucas-Kanade tracker on top of selected joints. It makes
# the fingertip signal much less sensitive to single-frame landmark jumps.
STABLE_HAND_ID_MAX_DISTANCE_PX = 220
FINGERTIP_OPTICAL_FLOW_STABILIZATION = True
OPTICAL_FLOW_LANDMARK_IDS = (2, 4, 5, 8, 9, 12, 13, 16, 17, 20)
OPTICAL_FLOW_WINDOW_SIZE = 25
OPTICAL_FLOW_MAX_LEVEL = 3
OPTICAL_FLOW_MAX_ERROR = 38.0
OPTICAL_FLOW_FORWARD_BACKWARD_CHECK = True
OPTICAL_FLOW_MAX_BACKTRACK_ERROR_PX = 6.0
OPTICAL_FLOW_RAW_WEIGHT = 0.55
OPTICAL_FLOW_OUTLIER_RAW_WEIGHT = 0.12
OPTICAL_FLOW_OUTLIER_DISTANCE_PX = 32.0
OPTICAL_FLOW_MAX_POINT_STEP_PX = 55.0

# Experimental: local high-resolution fingertip refinement. MediaPipe provides
# the coarse 21-point hand pose; this pass searches a small patch in the original
# frame around each fingertip and nudges the point toward a strong distal edge.
# Keep disabled by default until a recorded-session benchmark proves it helps.
FINGERTIP_REFINEMENT_ENABLED = False
FINGERTIP_REFINEMENT_RADIUS_PX = 22
FINGERTIP_REFINEMENT_MAX_SHIFT_PX = 14
FINGERTIP_REFINEMENT_MIN_EDGE_SCORE = 28.0
FINGERTIP_REFINEMENT_BLEND_ALPHA = 0.45
FINGERTIP_REFINEMENT_FORWARD_BIAS = 0.65

HAND_LANDMARKER_MODEL_URL = (
    "https://storage.googleapis.com/mediapipe-models/hand_landmarker/"
    "hand_landmarker/float16/latest/hand_landmarker.task"
)
HAND_LANDMARKER_MODEL_PATH = "models/hand_landmarker.task"

PIANO_AREA_HEIGHT_RATIO = 0.84
PIANO_KEYBED_OPACITY = 0.92
PIANO_PLANE_TOP_INSET_RATIO = 0.09
PIANO_PLANE_TOP_LIFT_RATIO = 0.06
PIANO_PLANE_SHADOW_ALPHA = 0.30
HAND_CUTOUT_ENABLED = True
HAND_CUTOUT_HULL_PADDING = 24
HAND_CUTOUT_LINE_THICKNESS = 34
HAND_CUTOUT_BLUR_KERNEL = 17
HAND_CUTOUT_ALPHA = 0.94
SHOW_FINGERTIP_MARKERS = True

DEPTH_CONTACT_MODE = "assist"  # off, assist, required
DEPTH_CONTACT_THRESHOLD_M = 0.075
DEPTH_RELEASE_THRESHOLD_M = 0.14
DEPTH_SAMPLE_RADIUS_PX = 3
DEPTH_BASELINE_FRAMES = 8
DEPTH_MIN_CONFIDENCE = 0.35
DEPTH_AUTO_BASELINE_WHEN_UNCALIBRATED = False

DISPLAY_SCALE = 1.25
DISPLAY_WINDOW_WIDTH = 0
DISPLAY_WINDOW_HEIGHT = 0

DEPTH_KEYBED_WIDTH_RATIO = 0.96
DEPTH_KEYBED_LENGTH_TO_WIDTH_RATIO = 0.42
DEPTH_KEYBED_MIN_HEIGHT_RATIO = 0.24
DEPTH_KEYBED_MAX_HEIGHT_RATIO = 0.50
DEPTH_KEYBED_BOTTOM_MARGIN_RATIO = 0.035
DEPTH_KEYBED_TOP_SCALE = 0.84
DEPTH_KEYBED_MAX_ROLL_DEGREES = 12.0
